"""API route routers."""

from logosforge.api.routes import (
    assistant,
    canvas_plot,
    characters,
    comments,
    connector,
    dashboard,
    events,
    export,
    extraction,
    format_data,
    grammar,
    imports,
    intelligence,
    knowledge_graph,
    live_context,
    logos,
    notes,
    outline,
    plot,
    progressions,
    projects,
    psyke,
    quantum,
    scenes,
    search,
    structure,
    themes,
    timeline,
    voice,
    workflows,
    writing_modes,
)

# Ordered list of every router mounted under the /api prefix.
ALL_ROUTERS = [
    projects.router,
    live_context.router,
    search.router,
    scenes.router,
    structure.router,
    outline.router,
    plot.router,
    canvas_plot.router,
    timeline.router,
    progressions.router,
    psyke.router,
    notes.router,
    comments.router,
    characters.router,
    themes.router,
    dashboard.router,
    intelligence.router,
    workflows.router,
    knowledge_graph.router,
    quantum.router,
    extraction.router,
    format_data.router,
    assistant.router,
    logos.router,
    connector.router,
    export.router,
    events.router,
    voice.router,
    writing_modes.router,
    imports.router,
    grammar.router,
]

__all__ = ["ALL_ROUTERS"]
