"""QUANTUM Outliner — physics-inspired story plotting agent.

Public API. The metaphors (relativity, uncertainty, wavefunction) are
abstract narrative models, not physics simulation.

Quick reference:
    generate_outline(db, pid, premise)            → starting branches
    generate_branches(db, pid, situation)         → next-move options
    reframe(scene_text, pov, db, pid)             → POV-shifted reading
    detect_weak_scenes(db, pid)                   → uncertainty zones
    collapse_branch(db, pid, wf_id, branch_id)    → commit, update PSYKE
    list_active_wavefunctions(pid)                → live branches
"""

from logosforge.quantum_outliner.collapse import apply_proposal
from logosforge.quantum_outliner.lookahead_cache import (
    MAX_BRANCHES_PER_NODE,
    MAX_DEPTH,
    LookaheadCache,
    evaluate_lookahead_cached,
    get_cache,
    invalidate_lookahead,
    submit_lookahead_async,
)
from logosforge.quantum_outliner.core import (
    QuantumResult,
    collapse_branch,
    compare_branches,
    detect_weak_scenes,
    explain_branches,
    generate_branches,
    generate_outline,
    get_decision_history,
    list_active_wavefunctions,
    reframe,
)
from logosforge.quantum_outliner.persistence import (
    export_quantum_state,
    import_quantum_state,
    load_state,
    save_state,
)
from logosforge.quantum_outliner.llm_evaluator import (
    build_eval_prompt,
    evaluate_branches as llm_evaluate_branches,
    score_with_llm,
)
from logosforge.quantum_outliner.scoring import (
    BEAT_PHASE_MAP,
    CollapseRecommendation,
    ComparisonEntry,
    ComparisonTable,
    ENSEMBLE_ALPHA,
    EXTENDED_PARETO_OBJECTIVES,
    FACTOR_CHIP_LABELS,
    FACTOR_LABELS,
    GOAL_FACTOR_MAP,
    GOAL_PRESET_NAMES,
    GOAL_PRESETS,
    LEARNING_RATE,
    MAX_COMPARE,
    PHASE_MULTIPLIERS,
    PRESET_NAMES,
    QuantumGoals,
    SCORING_PRESETS,
    SELECTION_MODES,
    UNIFIED_WEIGHTS,
    adapt_weights,
    apply_beat_bias,
    build_comparison,
    compute_unified_score,
    check_constraints,
    compute_blended_goal_score,
    compute_goal_score,
    compute_pareto_front,
    evaluate_lookahead,
    compute_probabilities,
    compute_tradeoff_chips,
    ensemble_combine,
    explain_factors,
    explain_goal_reasoning,
    explain_wavefunction,
    format_branch_chips,
    format_comparison,
    format_goals_panel,
    format_pareto_recommendation,
    format_recommendation,
    get_beat_phase,
    goals_from_preset,
    parse_constraint,
    parse_goal_constraint,
    recommend_collapse,
    recommend_pareto,
    score_with_heuristic,
    select_comparison_branches,
)
from logosforge.quantum_outliner.state import (
    OUTLINE_MODES,
    STRUCTURE_MODES,
    Branch,
    NarrativeState,
    OutlineMode,
    QuantumPossibility,
    StateDelta,
    Wavefunction,
    get_outline_mode,
    get_state,
    reset_state,
)

__all__ = [
    "LookaheadCache",
    "MAX_BRANCHES_PER_NODE",
    "MAX_DEPTH",
    "OUTLINE_MODES",
    "OutlineMode",
    "QuantumPossibility",
    "QuantumResult",
    "Branch",
    "NarrativeState",
    "STRUCTURE_MODES",
    "StateDelta",
    "Wavefunction",
    "CollapseRecommendation",
    "BEAT_PHASE_MAP",
    "FACTOR_LABELS",
    "GOAL_FACTOR_MAP",
    "GOAL_PRESET_NAMES",
    "GOAL_PRESETS",
    "LEARNING_RATE",
    "PHASE_MULTIPLIERS",
    "PRESET_NAMES",
    "SCORING_PRESETS",
    "ENSEMBLE_ALPHA",
    "EXTENDED_PARETO_OBJECTIVES",
    "UNIFIED_WEIGHTS",
    "adapt_weights",
    "compute_unified_score",
    "apply_beat_bias",
    "apply_proposal",
    "check_constraints",
    "compute_blended_goal_score",
    "compute_goal_score",
    "compute_pareto_front",
    "evaluate_lookahead",
    "evaluate_lookahead_cached",
    "get_cache",
    "invalidate_lookahead",
    "submit_lookahead_async",
    "compute_tradeoff_chips",
    "FACTOR_CHIP_LABELS",
    "format_branch_chips",
    "format_goals_panel",
    "get_beat_phase",
    "goals_from_preset",
    "collapse_branch",
    "compare_branches",
    "ComparisonEntry",
    "ComparisonTable",
    "compute_probabilities",
    "ensemble_combine",
    "explain_branches",
    "explain_factors",
    "explain_goal_reasoning",
    "explain_wavefunction",
    "format_pareto_recommendation",
    "format_recommendation",
    "build_comparison",
    "format_comparison",
    "MAX_COMPARE",
    "parse_constraint",
    "parse_goal_constraint",
    "QuantumGoals",
    "recommend_collapse",
    "select_comparison_branches",
    "recommend_pareto",
    "SELECTION_MODES",
    "build_eval_prompt",
    "llm_evaluate_branches",
    "score_with_heuristic",
    "score_with_llm",
    "detect_weak_scenes",
    "export_quantum_state",
    "generate_branches",
    "generate_outline",
    "get_decision_history",
    "get_outline_mode",
    "get_state",
    "import_quantum_state",
    "list_active_wavefunctions",
    "load_state",
    "reframe",
    "reset_state",
    "save_state",
]
